### ISSUE TITLE
Why not consolidate the scripts into a single file?

### ISSUE THREAD

**Issue by shashankshirke** [Pranavoro/kite_kill_switch#1]
Hi @Pranavoro 
This project looks interesting. I am planning to try it out. 

Just wondering what's the logic behind having separate files for the login, logger and the kill_switch functionalities? Why not just consolidate all functions into the main positions_kill_switch file? A separate config file is understandable.

**Comment by Pranavoro** [comment]
Hi @shashankshirke , All the files, in fact, are consolidated in the positions_kill_switch.py file. I have commented out line no. 175 to disable the segment kill switch which requires browser automation, which is not desired for everyone.
I agree I could've handled it better, but I haven't had the time recently. Maybe I'll add them in future updates.
The files are separate because you can use whichever function you like individually. 
For eg. If you want you can separately use kill_switch.py without using positions_kill_switch, as all of them serve a different purpose. I am however planning to add directories to avoid any confusion.

**Comment by shashankshirke** [comment]
Okay understood, thanks for the explanation.

I liked how you have implemented the ability to use multiple client_ids.
Looking forward to future updates.
