### ISSUE TITLE
Why use "net" instead of "day" when exiting all positions?

### ISSUE THREAD

**Issue by shashankshirke** [Pranavoro/kite_kill_switch#2]
Hi @Pranavoro 

In the exit_all_positions() function, on Ln 128 why is the positions['net'] being used instead of positions['day']?

For intraday positions, shouldn't positions['day'] be used as per the official docs: https://kite.trade/docs/connect/v3/portfolio/#positions

**Comment by Pranavoro** [comment]
Hi @shashankshirke we cannot use positions['day'] because when we're placing orders for the kill switch, it might open new positions instead of closing the ones which were open.

[eg. to explain the difference.](https://kite.trade/forum/discussion/5107/difference-between-net-and-day-in-position#:~:text=Day%20and%20net%20positions%20affects,else%20both%20will%20be%20same.&text=and%20today%20you%20sold%2075%20Qty%20of%20NIFTY%20future.)
